{% set name = "storm" %}
{% set version = "0.26" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/storm-{{ version }}.tar.gz
  sha256: 9fe4f638fdd58494823bd156eb63fc32ffc41dd292e314fed3efe74a55c87f3e

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - storm
    - storm.databases
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://storm.canonical.com
  summary: Storm is an object-relational mapper (ORM) for Python developed at Canonical.
  license: LGPL-2.1-or-later
  license_file: LICENSE
  doc_url: https://storm.canonical.com
  dev_url: https://launchpad.net/storm

extra:
  recipe-maintainers:
    - beenje
