{% set name = "storm" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/storm-{{ version }}.tar.gz
  sha256: 9b434d3ce3248bd1fc86b8406c5dcc3350585d4512f1a7f6731aa97688ead841

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - python
    - six

test:
  imports:
    - storm
    - storm.databases
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://storm.canonical.com
  summary: Storm is an object-relational mapper (ORM) for Python developed at Canonical.
  license: LGPL-2.1-or-later
  license_file: LICENSE
  doc_url: https://storm.canonical.com
  dev_url: https://launchpad.net/storm

extra:
  recipe-maintainers:
    - beenje
