schema_version: 1

context:
  name: storm
  version: "1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/storm-${{ version }}.tar.gz
  sha256: f8d3b1239e3c49f44ec273856fdead74fa54627045fa59db5df4dc97b02e999c

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - packaging >=14.1

tests:
  - python:
      imports:
        - storm
        - storm.databases
      pip_check: true

about:
  summary: Storm is an object-relational mapper (ORM) for Python developed at Canonical.
  license: LGPL-2.1-or-later
  license_file: LICENSE
  homepage: https://storm.canonical.com
  repository: https://launchpad.net/storm
  documentation: https://storm-orm.readthedocs.io

extra:
  recipe-maintainers:
    - beenje
